# Global settings for the benchmark
training_id: "example_config_minimal"
surrogates: ["FullyConnected", "LatentPoly"]
batch_size: [65536, 512]
epochs: [20, 20]
dataset:
  name: "lotka_volterra"
  tolerance: 1e-15
devices: ["cpu"]

# # Models to train
# interpolation:
#   enabled: False
#   intervals: [2, 3, 4, 5, 6, 7, 8, 9, 10]
# extrapolation:
#   enabled: False
#   cutoffs: [50, 60, 70, 80, 90]
# sparse:
#   enabled: False
#   factors: [2, 4, 8, 16, 32]
# batch_scaling:
#   enabled: False
#   sizes: [1/16, 1/8, 1/4, 1/2]
# uncertainty:
#   enabled: False
#   ensemble_size: 5 # Number of models for deep ensemble

# # Evaluations during benchmark
losses: True
gradients: True
timing: True
compute: True
compare: True # Whether to compare the surrogates
iterative: True
