# Full configuration template for run_training.py and run_eval.py

# Global settings
training_id: "example_run"
surrogates: ["MultiONet"]
devices: ["cpu"]
seed: 42
verbose: False

# Training settings
batch_size: [65536]
epochs: [200]
checkpoint: False

# Dataset settings
dataset:
  name: "osu2008"
  log10_transform: True
  log10_transform_params: False
  normalise: "minmax" # "standardise", "minmax", "disable"
  normalise_per_species: False
  tolerance: 1e-25
  log_timesteps: False
  use_optimal_params: True
  subset_factor: 1

# Models to train
interpolation:
  enabled: False
  intervals: [2, 3, 4, 5, 6, 7, 8, 9, 10]
extrapolation:
  enabled: False
  cutoffs: [50, 60, 70, 80, 90]
sparse:
  enabled: False
  factors: [2, 4, 8, 16, 32]
batch_scaling:
  enabled: False
  sizes: ["1/16", "1/8", "1/4", "1/2"]
uncertainty:
  enabled: False
  ensemble_size: 5 # Number of models for deep ensemble

# Evaluations during benchmark
losses: True
iterative: False
gradients: True
timing: True
compute: True
compare: True

# Metric options
relative_error_threshold: 1e-10
error_percentile: 99
