seed: 123
tuning_id: "sqlite_quickstart"

storage:
  backend: "sqlite"
  path: "tuned/sqlite_quickstart/sqlite_quickstart.db"

dataset:
  name: "osu2008"
  log10_transform: true
  normalise: minmax

devices: ["cuda:2", "cuda:3"]
prune: false
multi_objective: false

surrogates:
  - name: "MultiONet"
    batch_size: 1024
    epochs: 128
    trials: 5
    optuna_params:
      hidden_size:
        type: int
        low: 32
        high: 128
      learning_rate:
        type: float
        low: 1.0e-4
        high: 5.0e-3
        log: true
      activation:
        type: categorical
        choices: ["ReLU", "GELU"]
